# Generated by Django 5.0.7 on 2024-07-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=100)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.IntegerField()),
                ('rsi', models.FloatField()),
                ('macd', models.FloatField()),
                ('timeframe', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
