# Generated by Django 5.0.7 on 2024-07-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_chartdata_date_alter_chartdata_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartdata',
            name='macd',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='chartdata',
            name='rsi',
            field=models.FloatField(null=True),
        ),
    ]
